name: cooksoc
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^1.3.0

  # UI
  font_awesome_flutter: ^9.1.0
  flutter_slidable: ^0.6.0
  flutter_svg: ^0.22.0
  animations: ^2.0.0
  date_format: ^2.0.2
  adaptive_breakpoints: ^0.0.4
  overlay_support: ^1.2.1
  flutter_portal: ^0.4.0

  package_info_plus: ^1.0.2
  url_launcher: ^6.0.6
  connectivity_plus: ^1.0.2
  injectable: ^1.4.1
  get_it: ^7.1.3
  universal_platform: ^1.0.0-nullsafety
  shared_preferences: ^2.0.6
  freezed_annotation: ^0.14.2
  equatable: ^2.0.2
  email_validator: ^2.0.1
  json_annotation: ^4.0.1
  rxdart: ^0.27.1
  timeago: ^3.1.0
  dart_date: ^1.1.0
  in_app_review: ^2.0.2
  enum_to_string: ^2.0.1
  tuple: ^2.0.0
  strings: ^0.2.1
  collection: ^1.15.0
  stream_transform: ^2.0.0
  auto_route: ^2.2.0
  google_fonts: ^2.1.0
  riverpod: ^0.14.0+3
  flutter_riverpod: ^0.14.0+3
  ferry: ^0.10.3
  gql_http_link: ^0.4.0
  logging: ^1.0.1

dependency_overrides:
  analyzer: 1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  ############################## Code Generation ###############################
  # Run:
  # flutter packages pub run build_runner build --delete-conflicting-outputs
  # Or run:
  # flutter packages pub run build_runner watch --delete-conflicting-outputs
  # To execute the code generation process either once or for every file change
  # with the watch command
  # Official code generation package for Dart
  build_runner: ^2.0.4

  auto_route_generator: ^2.1.0

  flutter_gen_runner: ^3.1.1

  freezed: ^0.14.2

  injectable_generator: ^1.4.1

  json_serializable: ^4.1.3
  
  ferry_generator: ^0.4.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter_gen:
  output: lib/core/asset_gen # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/svg/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: BalsamiqSans
      fonts:
        - asset: fonts/BalsamiqSans-Regular.ttf
          weight: 400
        - asset: fonts/BalsamiqSans-Italic.ttf
          style: italic
          weight: 400
        - asset: fonts/BalsamiqSans-Bold.ttf
          weight: 700
        - asset: fonts/BalsamiqSans-BoldItalic.ttf
          style: italic
          weight: 700
  
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
